name: anoma-explorer-indexer
contracts:
  - name: ProtocolAdapter
    handler: src/EventHandlers.ts
    events:
      - event: "TransactionExecuted(bytes32[] tags, bytes32[] logicRefs)"
      - event: "ActionExecuted(bytes32 actionTreeRoot, uint256 actionTagCount)"
      - event: "ForwarderCallExecuted(address indexed untrustedForwarder, bytes input, bytes output)"
      - event: "ResourcePayload(bytes32 indexed tag, uint256 index, bytes blob)"
      - event: "DiscoveryPayload(bytes32 indexed tag, uint256 index, bytes blob)"
      - event: "ExternalPayload(bytes32 indexed tag, uint256 index, bytes blob)"
      - event: "ApplicationPayload(bytes32 indexed tag, uint256 index, bytes blob)"
      - event: "CommitmentTreeRootAdded(bytes32 root)"
field_selection:
  transaction_fields:
    - "hash"
networks:
  - id: 42161
    start_block: 0
    contracts:
    - name: ProtocolAdapter
      address:
        - "0x212f275c6dd4829cd84abdf767b0df4a9cb9ef60"
  - id: 1
    start_block: 0
    contracts:
    - name: ProtocolAdapter
      address:
        - "0xdd4f4f0875da48ef6d8f32acb890ec81f435ff3a"
  - id: 11155111
    start_block: 0
    contracts:
    - name: ProtocolAdapter
      address:
        - "0xc63336a48d0f60fad70ed027dfb256908bbd5e37"
unordered_multichain_mode: true
